services:
  ical-formatter-api:
    build: .
    image: ical-formatter-api:latest
    container_name: ical-formatter-api
    ports:
      - "8081:8080"
    restart: unless-stopped
    volumes:
      - ./data:/app